# Cache bust: 2025-07-30-06:00
[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.build]
cmds = ['composer install --no-dev --ignore-platform-reqs --no-scripts --prefer-dist', 'php artisan config:clear', 'php artisan cache:clear']

[phases.start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'