services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000" 
    networks:
      - laravel-network
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1224832
      MYSQL_DATABASE: agrilink
      MYSQL_USER: agrilink_user
      MYSQL_PASSWORD: supersecurepass
    ports:
      - "3307:3306"
    volumes:
      - ./agrilink_dump.sql:/docker-entrypoint-initdb.d/agrilink_dump.sql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1224832
    ports:
      - "8080:80"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
